Blog\Entity\Post:
    name: post
    manager: Blog\Manager\PostManager
    columns:
        id:
         type: int
         required: false
        title:
         type: string
         required: true
        added:
         type: datetime
         required: true
        updated:
         type: datetime
         required: false
        published:
         type: boolean
         required: false
        content:
         type: string
         required: true
        category:
         type: int
         required: true
        number:
         type: int
         required: false

Blog\Entity\Comment:
    name: comment
    manager: Blog\Manager\CommentManager
    columns:
        id:
         type: int
         required: false
        author:
         type: string
         required: true
        added:
         type: datetime
         required: true
        updated:
         type: datetime
         required: false
        published:
         type: boolean
         required: false
        content:
         type: string
         required: true
        postId:
         type: int
         required: true

Blog\Entity\Category:
    name: category
    manager: Blog\Manager\CategoryManager
    columns:
        id:
         type: int
         required: false
        name:
         type: string
         required: true

Blog\Entity\User:
    name: user
    manager: Blog\Manager\UserManager
    columns:
        id:
          type: int
          required: false
        username:
          type: string
          required: true
        password:
          type: string
          required: true