Blog\Entity\Post:
    name: post
    manager: Blog\Manager\PostManager
    columns:
        id: { type: 'int' }
        title: { type: 'string' }
        slug: { type: 'string' }
        added: { type: 'datetime' }
        updated: { type: 'datetime' }
        published: { type: 'boolean' }
        content: { type: 'string' }

Blog\Entity\Comment:
    name: comment
    manager: Blog\Manager\CommentManager
    columns:
        id: { type: 'int' }
        author: { type: 'string' }
        added: { type: 'datetime' }
        updated: { type: 'datetime' }
        published: { type: 'boolean' }
        content: { type: 'string' }
        post: { type: 'int' }
