insertComment:
    path: /comment/insert
    parameters: {}
    controller: Blog\Controller\CommentController
    action: insertAction
insertBillet:
    path: /chapitres/insert
    parameters: {}
    controller: Blog\Controller\PostController
    action: insertAction

deleteBillet:
    path: /chapitres/delete/:id
    parameters: {id: '[\d]+'}
    controller: Blog\Controller\PostController
    action: deleteAction

editBillet:
    path: /chapitres/edit/:id
    parameters: {id: '[\d]+'}
    controller: Blog\Controller\PostController
    action: editAction

nextChapter:
    path: /chapitres/next
    parameters: {}
    controller: Blog\Controller\Postcontroller
    action: nextAction

previousChapter:
    path: /chapitres/previous
    parameters: {}
    controller: Blog\Controller\Postcontroller
    action: previousAction

idChapter:
    path: /chapitres/:id
    parameters: {id:  '[\d]+'}
    controller: Blog\Controller\PostController
    action: showAction

slugChapter:
    path:  /chapitres/:slug
    parameters: {slug:  '([A-Za-z0-9]+-[A-Za-z0-9]+)+$'}
    controller: Blog\Controller\PostController
    action: showAction

chapter:
    path: /chapitres
    parameters: {}
    controller: Blog\Controller\PostController
    action: listAction

login:
    path: /login
    parameters: {}
    controller: Blog\Controller\UserController
    action: loginAction

admin:
    path: /admin
    parameters: {}
    controller: Blog\Controller\BackController
    action: homeAction

home:
    path: /
    parameters: {}
    controller: Blog\Controller\HomeController
    action: homeAction