editBillet:
    path: /billets/edit/:id
    parameters: {id: '[\d]+'}
    controller: Blog\Controller\PostController
    action: editAction

billet:
    path:  /billets/:id
    parameters: {id:  '[\d]+'}
    controller: Blog\Controller\PostController
    action: showAction

billets:
    path: /billets
    controller: Blog\Controller\PostController
    action: listAction

home:
    path: /
    controller: Blog\Controller\HomeController
    action: homeAction