insertBillet:
    path: /billets/insert
    parameters:
    controller: Blog\Controller\PostController
    action: insertAction

deleteBillet:
    path: /billets/delete/:id
    parameters: {id: '[\d]+'}
    controller: Blog\Controller\PostController
    action: deleteAction

editBillet:
    path: /billets/edit/:id
    parameters: {id: '[\d]+'}
    controller: Blog\Controller\PostController
    action: editAction


billetSlug:
    path:  /billets/:slug
    parameters: {slug:  '([A-Za-z0-9]+-[A-Za-z0-9]+)+$'}
    controller: Blog\Controller\PostController
    action: showAction

billet:
    path:  /billets/:id
    parameters: {id:  '[\d]+'}
    controller: Blog\Controller\PostController
    action: showAction

billets:
    path: /billets
    parameters:
    controller: Blog\Controller\PostController
    action: listAction

home:
    path: /
    parameters:
    controller: Blog\Controller\HomeController
    action: homeAction