billets:
    path:  /billets/:id
    parameters: {id:  '[\d]+'}
    controller: Blog\Controller\PostController
    action: showAction

home:
    path: /
    controller: Blog\Controller\HomeController
    action: homeAction