insertComment:
    path: /comment/insert
    parameters: {}
    controller: Blog\Controller\CommentController
    action: insertAction
insertBillet:
    path: /chapitres/insert
    parameters: {}
    controller: Blog\Controller\PostController
    action: insertAction

deleteBillet:
    path: /chapitres/delete/:id
    parameters: {id: '[\d]+'}
    controller: Blog\Controller\PostController
    action: deleteAction

editBillet:
    path: /chapitres/edit/:id
    parameters: {id: '[\d]+'}
    controller: Blog\Controller\PostController
    action: editAction

nextChapter:
    path: /chapitres/next
    parameters: {}
    controller: Blog\Controller\PostController
    action: nextAction

previousChapter:
    path: /chapitres/previous
    parameters: {}
    controller: Blog\Controller\PostController
    action: previousAction

idChapter:
    path: /chapitres/:id
    parameters: {id:  '[\d]+'}
    controller: Blog\Controller\PostController
    action: showAction

numberChapter:
    path: /chapitres/chapitre-:number
    parameters: {number:  '[\d]+'}
    controller: Blog\Controller\PostController
    action: showAction

chapters:
    path: /chapitres
    parameters: {}
    controller: Blog\Controller\PostController
    action: listAction

login:
    path: /login
    parameters: {}
    controller: Blog\Controller\UserController
    action: loginAction

about:
    path: /a-propos
    parameters: {}
    controller: Blog\Controller\PostController
    action: aboutAction

adminEdito:
    path: /admin/edito
    parameters: {}
    controller: Blog\Controller\BackController
    action: editoAction

adminSynopsis:
    path: /admin/synopsis
    parameters: {}
    controller: Blog\Controller\BackController
    action: synopsisAction

adminChapterEdit:
    path: /admin/chapter/edit/:id
    parameters: {id: '[\d]+'}
    controller: Blog\Controller\BackController
    action: chapterEditAction

adminChapterDelete:
    path: /admin/chapter/delete/:id
    parameters: {id: '[\d]+'}
    controller: Blog\Controller\BackController
    action: chapterDeleteAction

adminChapterNew:
    path: /admin/chapter/new
    parameters: {}
    controller: Blog\Controller\BackController
    action: chapterNewAction

adminChapters:
    path: /admin/chapters
    parameters: {}
    controller: Blog\Controller\BackController
    action: chaptersAction

admimChapters:
    path: /admin/chapter/:id
    parameters: {id: '[\d]+'}
    controller: Blog\Controller\BackController
    action: chapterAction

adminCommentsChapter:
    path: /admin/comments/:id
    parameters: {id: '[\d]+?'}
    controller: Blog\Controller\BackController
    action: commentsAction

adminCommentsModerate:
    path: /admin/comments/moderate
    parameters: {}
    controller: Blog\Controller\BackController
    action: commentsModerateAction

adminComments:
    path: /admin/comments
    parameters: {}
    controller: Blog\Controller\BackController
    action: commentsAction

adminComment:
    path: /admin/comment/:id
    parameters: {id: '[\d]+'}
    controller: Blog\Controller\BackController
    action: commentAction

adminCommentEdit:
    path: /admin/comment/edit/:id
    parameters: {id: '[\d]+'}
    controller: Blog\Controller\BackController
    action: commentEditAction

adminCommentDelete:
    path: /admin/comment/delete/:id
    parameters: {id: '[\d]+'}
    controller: Blog\Controller\BackController
    action: commentDeleteAction

adminUser:
    path: /admin/user
    parameters: {}
    controller: Blog\Controller\BackController
    action: userAction


adminAbout:
    path: /admin/about
    parameters: {}
    controller: Blog\Controller\BackController
    action: aboutAction


admin:
    path: /admin
    parameters: {}
    controller: Blog\Controller\BackController
    action: homeAction

jsonComments:
    path: /comments/:id/:offset/:limit
    parameters: {id:  '[\d]+', offset: '[\d]+', limit: '[\d]+'}
    controller: Blog\Controller\CommentController
    action: getAction

home:
    path: /
    parameters: {}
    controller: Blog\Controller\HomeController
    action: homeAction
