twig:
  class: App\Templating\Templating
  params: { file: ../views/ }

slug:
  class: Blog\Services\Slug
  params: {}

database:
  class: App\Orm\Database
  params: { file: ../config/database.yml, metas: ../config/entities.yml }

request:
  class: App\Http\Request\Request
  params: {}

readchapters:
  class: Blog\Services\ReadChapters
  params: {}

form:
  class: Blog\Services\Form
  params: { metas: ../config/entities.yml }

bag:
  class: Blog\Services\MessagesBag
  params: {}