twig:
  class: App\Templating\Templating
  params: { file: ../views/ }

slug:
  class: Blog\Services\Slug
  params:

database:
  class: App\Orm\Database
  params: { file: ../config/database.yml, metas: ../config/entities.yml }